### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by angelabad** [gnustavo/JIRA-Client#10]
Hi, packaging for Debian we found these spelling errors:

--- a/lib/JIRA/Client.pm
+++ b/lib/JIRA/Client.pm
@@ -1374,14 +1374,14 @@
 
 =back
 
-The method retuns the value returned by the
+The method returns the value returned by the
 B<addBase64EncodedAttachmentsToIssue> API method.
 
 In the example below, we attach three files to the issue TST-1. The
 first is called C<file1.txt> and its contents are read from
 C</path/to/file1.txt>. The second is called C<text.txt> and its
 contents are read from C</path/to/file2.txt>. the third is called
-C<me.jpg> and its contents are read from the object refered to by
+C<me.jpg> and its contents are read from the object referred to by
 C<$fh>.
 
     $jira->attach_files_to_issue('TST-1',
@@ -1399,7 +1399,7 @@
 attachments are specified by a HASHREF in which the keys denote the
 file names and the values their contents.
 
-The method retuns the value returned by the
+The method returns the value returned by the
 B<addBase64EncodedAttachmentsToIssue> API method.
 
 =head2 B<filter_issues_unsorted> FILTER [, LIMIT]

Cheers,

**Comment by gnustavo** [comment]
Hi Angel. Thanks for the fixes. I'll cut another release with them.

However, this module is deprecated. Have you noticed it? I suggest you remove it from future Debian versions.
