### ISSUE TITLE
JIRA::Client does not work with SOAP::Lite 0.715

### ISSUE THREAD

**Issue by eserte** [gnustavo/JIRA-Client#2]
With SOAP::Lite 0.714 things still work. But with SOAP::Lite 0.715 I just get

```
Undefined subroutine &main:: called at /opt/perl-5.14.2/lib/site_perl/5.14.2/SOAP/Lite.pm line 1220, <STDIN> line 1.
```

when calling the SOAP::Lite constructor.

I checked with JIRA::Client v0.37-3-g43a9ac8 and older versions.

Regards,
    Slaven

**Comment by gnustavo** [comment]
Can you please check again with JIRA::Client 0.39? I've tested it myself and it works in my environment.

Thanks.

**Comment by eserte** [comment]
I tried it with SOAP::Lite 0.715 and JIRA::Client 0.40 on a perl 5.16.0, and it works.
