### ISSUE TITLE
Problem when using set_filter_iterator/next_issue

### ISSUE THREAD

**Issue by ghost** [gnustavo/JIRA-Client#4]
As best I can tell, the problem has to do with the is_has_ref function.A call is made from autoload, the function is_hash_ref can't be found, so autoload is called again , if falls throught the if statements and tried to invole  $self->{soap}->call($method, $self->{auth}, @args);

I'm getting this error:

Can't call method "call" on an undefined value at D:/Apps/Perl/site/lib/JIRA/Client.pm line 962.
 at jira.pl line 30

When running this script:
# !perl -w

use strict;
use SOAP::Lite;
use Data::Dumper;
use JIRA::Client;

my $JIRA_URL = 'http://jira-qa.bankofamerica.com:9084';

sub PrintResult
{
    my ($string, $object) = @_;

```
my $whitespace = '';

my $type = ref($object);
print "$string ($type):\n";

if    (not $type)        { print "\t$object\n"; }        # Not a reference
elsif ($type eq 'ARRAY') { PrintArray($object, "$whitespace\t") }
else                     { PrintHash($object,  "$whitespace\t") }
```

}

print "About to connect to $JIRA_URL\n";
my $jira = JIRA::Client->new($JIRA_URL, 'nbkc15p', 'xyzzy');
# Get filter

print "Before set filter\n";
$jira->set_filter_iterator('11520');
print "after set filter\n";
while (my $issue = $jira->next_issue())
{
    print 'Issue: ' . Dumper($issue);
}

**Comment by gnustavo** [comment]
Can you tell me which version of Perl, JIRA::Client and Data::Util modules you're using? Like this:

```
$ perl -MJIRA::Client -e 'print "$^V, $JIRA::Client::VERSION, $Data::Util::VERSION\n"'
v5.14.2, 0.40, 0.60
```

**Comment by ghost** [comment]
Hi,

Here is the result: v5.14.2, 0.34

Thanks,
Rich

---

Richard S. Scire
VP; Consultant - Systems Engineering
Developer Environment Tools Support (DETS)
SDLC Distributed Tools Supporthttp://sdlc.bankofamerica.com/
Bank of America

980-386-9552 (Office)
Richard.Scire@BankofAmerica.commailto:Richard.Scire@BankofAmerica.com

**Comment by ghost** [comment]
Hi,

Please close this bug. I had an older version of this package. It was the latest according to CPAN but PPM had a later version.

Thanks,
Rich

---

Richard S. Scire
VP; Consultant - Systems Engineering
Developer Environment Tools Support (DETS)
SDLC Distributed Tools Supporthttp://sdlc.bankofamerica.com/
Bank of America

980-386-9552 (Office)
Richard.Scire@BankofAmerica.commailto:Richard.Scire@BankofAmerica.com
