### ISSUE TITLE
Question about version in jira

### ISSUE THREAD

**Issue by lickou** [gnustavo/JIRA-Client#5]
Hello,
I'm new at using Jira-Client and I was wondering if there is a way of modifying a version in jira like adding description or delete a version?? the only functions that I can found is addVersion (but I cannot add a description), archiveVersion, getVersions and releasVersion.

Thanks

**Comment by gnustavo** [comment]
Unfortunately, not. You're constrained by the JIRA SOAP API's exposed functionality, which offers the methods you already found.

JIRA's SOAP API isn't evolving anymore. They're developing a REST API which should be more complete by now. If your needs aren't met by the SOAP API you should look at their REST API. Unfortunately, JIRA::Client does not support it yet. There's a JIRA::Client::REST module at CPAN by another person. You should take a look at it.

**Comment by lickou** [comment]
ok I'll take a look at REST API
Thanks
