### ISSUE TITLE
Problem with jira->attach_files_to_issue

### ISSUE THREAD

**Issue by immortalgr** [gnustavo/JIRA-Client#6]
Hi , 

 I am having trouble attaching a file on a jira ticket , the error I am getting is :

ns1:Client, No such operation 'addBase64EncodedAttachmentsToIssue' at ./1.pl line 88

Line 88 is the actual attach command : 

my $dymmy = $jira->attach_files_to_issue ( 'JIRA-TICKET' , '/home/nkoz/vlc-log.txt' );

Some info on versions : 

perl -MJIRA::Client -e 'print "$^V, $JIRA::Client::VERSION, $Data::Util::VERSION\n"'
v5.14.2, 0.40, 0.59

Any idea what is going wrong ? 

Thank you in advance ..

**Comment by gnustavo** [comment]
Hi,

The addBase64EncodedAttachmentsToIssue method was introduced in the JIRA SOAP API in JIRA version 4.0. Are you using an older version of JIRA?

Gustavo.

**Comment by immortalgr** [comment]
We are using v3.12 , so is there an alternative way to attach files ? 

Thanx,
Nickitas

**Comment by gnustavo** [comment]
Before JIRA 4.0 you had to use the addAttachmentsToIssue method. But as I recall it was extremely slow... I don't know why.

JIRA::Client doesn't have a nice way to attach using that old method. You have to use it directly passing the needed arguments [as specified](https://docs.atlassian.com/rpc-jira-plugin/4.4/com/atlassian/jira/rpc/soap/JiraSoapService.html).
