### ISSUE TITLE
Can't call method "fault" on an undefined value at ...

### ISSUE THREAD

**Issue by mlbright** [gnustavo/JIRA-Client#8]
hello!

I'm getting a SOAP::Lite error when I try to ->getIssue, when the issue exists in JIRA. The error is happening here:

```
croak $call->faultcode(), ', ', $call->faultstring()
    if defined $call->fault();
```

in sub AUTOLOAD, where $call is undefined. I'm not sure how to handle this. Should you be checking if $call is defined, or is this something so wrong with the response from JIRA that it should never happen? I'm using version 0.40 of JIRA::Client.

**Comment by gnustavo** [comment]
Hmm... I don't know. Can you trace the SOAP calls and post it here? Simply insert this line right before the invocation of getIssue:

``` Perl
SOAP::Lite->import(+trace => 'all');
```

Then, redirect the stderr of your script to a file and post it here, please. (Check to see if it isn't exposing any sensitive information. If you start the trace before creating the JIRA::Client object your password will end up in the file.) Perhaps we can figure this up from the trace.

**Comment by mlbright** [comment]
Thanks I will try that when I get a chance. This happens very infrequently and only for certain issues.
