### ISSUE TITLE
Inaccurate deprecation warning in v0.43

### ISSUE THREAD

**Issue by Keith-S-Thompson** [gnustavo/JIRA-Client#9]
In `v0.42`, the deprecation warning said:

> ... JIRA's SOAP API was deprecated ... on JIRA 6.0 and won't be available anymore on JIRA 7.0.

In `v0.43`, this was changed to:

> ... JIRA's SOAP API was deprecated ... on JIRA 6.0 and won't be available anymore on JIRA 8.0.

According to [this announcement](https://developer.atlassian.com/blog/2015/05/jira-soap-api-announcement/), the v0.42 warning is correct.

**Comment by gnustavo** [comment]
I think Atlassian changed their minds along the way. I vividly remember reading the first announcement telling that it would be removed in JIRA 7 and later another announcement telling that it would be removed in JIRA 8. And then, they change it back again to JIRA 7.

I could be wrong about that but then I wouldn't be the only one: https://bugs.chromium.org/p/gerrit/issues/detail?id=2907 :-)

Anyway, now that JIRA 7 is here we know the verdict... I'll cut another release to amend that.

Thanks!
